apiVersion: v1
kind: Secret
metadata:
  name: branchbase-secrets
  namespace: branchbase
type: Opaque
stringData:
  mongo-root-username: root
  mongo-root-password: example
  # Google OAuth (Update these in your cluster secrets manually)
  client-id: "YOUR_GOOGLE_CLIENT_ID"
  client-secret: "YOUR_GOOGLE_CLIENT_SECRET"
